/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lsc.ls.text.compression;

/**
 *
 * @author wiz
 */
public class Symbols {
                                                                                                                                  
    public static final String[] TABLE = {" ", //0                                                                         
                                            "0",                                                                                  
                                            "1",                                                                                  
                                            "2",                                                                                  
                                            "3",                                                                                  
                                            "4",                                                                                  
                                            "5",                                                                                  
                                            "6",                                                                                  
                                            "7",                                                                                  
                                            "8",                                                                                  
                                            "9", //10                                                                             
                                            "A",                                                                                  
                                            "B",                                                                                  
                                            "C",                                                                                  
                                            "D",                                                                                  
                                            "E",                                                                                  
                                            "F",                                                                                  
                                            "G",                                                                                  
                                            "H",                                                                                  
                                            "I",                                                                                  
                                            "J", //20                                                                             
                                            "K",                                                                                  
                                            "L",                                                                                  
                                            "M",                                                                                  
                                            "N",                                                                                  
                                            "O",                                                                                  
                                            "P",                                                                                  
                                            "Q",                                                                                  
                                            "R",                                                                                  
                                            "S",                                                                                  
                                            "T", //30                                                                             
                                            "U",                                                                                  
                                            "V",                                                                                  
                                            "W",                                                                                  
                                            "X",                                                                                  
                                            "Y",                                                                                  
                                            "Z",                                                                                  
                                            "a",                                                                                  
                                            "b",                                                                                  
                                            "c",                                                                                  
                                            "d", //40                                                                             
                                            "e",                                                                                  
                                            "f",                                                                                  
                                            "g",                                                                                  
                                            "h",                                                                                  
                                            "i",                                                                                  
                                            "j",                                                                                  
                                            "k",                                                                                  
                                            "l",                                                                                  
                                            "m",                                                                                  
                                            "n", //50                                                                             
                                            "o",                                                                                  
                                            "p",                                                                                  
                                            "q",                                                                                  
                                            "r",                                                                                  
                                            "s",                                                                                  
                                            "t",                                                                                  
                                            "u",                                                                                  
                                            "v",                                                                                  
                                            "w",                                                                                  
                                            "x", //60                                                                             
                                            "y",                                                                                  
                                            "z",                                                                                  
                                            "*",                                                                                  
                                            ".",                                                                                  
                                            ",",                                                                                  
                                            "?",                                                                                  
                                            "!",                                                                                  
                                            "/",                                                                                  
                                            "<",                                                                                  
                                            ">", // 70
                                            ":",      
                                            "-",                                                                                  
                                            "'",                                                                                  
                                            "\"",                                                                                  
                                            "%",                                                                                  
                                            "#",                                                                                  
                                            "&",                                                                                  
                                            "(",                                                                                  
                                            ")",                                                                                  
                                            "=", //80                                                                             
                                            "[",                                                                           
                                            "]",                                                                           
                                            "",                                                                           
                                            "",                                                                           
                                            "",                                                                           
                                            "|56|", // Blinking arrow                                                                          
                                            "|57|", // Line Feed                                                                          
                                            "|58|", // Yes/No                                                                          
                                            "|59|", // Wait                                                                          
                                            "|5A|", //90 // Numeric Value
                                            "|5A|", // Character name
                                            "\\UNUSED", 
                                            "\\UNUSED", 
                                            "|5A|", // Sentence End
                                            "|5A|", // Object Name
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "|5A|", // Clear Panel
                                            "\\UNUSED",
                                            "\\UNUSED", //100
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",
                                            "\\UNUSED",                                            
                                            "{DICT}",
                                            "{N}",
                                            "{D2}",
                                            "{#}",
                                            "{NAME}",
                                            "{LEADER}",
                                            "{ITEM}",
                                            "{SPELL}",
                                            "{CLASS}",
                                            "{W2}",
                                            "{D1}",
                                            "{D3}",
                                            "{W1}",
                                            "{CLEAR}",
                                            "{NAME",
                                            "{COLOR",
                                            "(START/EOL)",
                                            "\\UNUSED"
                                            };
        
    
    
    
}
